module.exports = {
    main_menu: require("./main_menu").main_menu,
    main_menu_after_start: require("./main_menu_after_start").main_menu_after_start,
    start: require("./start").start,
    main_information: require("./main_information").main_information,
    contact_information: require("./contact_information").contact_information,
    respond: require("./respond").respond,
    call_menu: require("./call_menu").call_menu,
    call_request: require("./call_request").call_request,
    products_menu: require("./products_menu").products_menu,
    list_of_products_categories: require("./list_of_products_categories").list_of_products_categories,
    list_of_products: require("./list_of_products").list_of_products,
    information_about_product: require("./information_about_product").information_about_product,
    buy_request: require("./buy_request").buy_request,
    product_mark_menu: require("./product_mark_menu").product_mark_menu,
    product_mark: require("./product_mark").product_mark,
    list_of_products_sale: require("./list_of_products_sale").list_of_products_sale,
    information_about_product_sale: require("./information_about_product_sale").information_about_product_sale,
    buy_request_sale: require("./buy_request_sale").buy_request_sale,
    product_mark_menu_sale: require("./product_mark_menu_sale").product_mark_menu_sale,
    product_mark_sale: require("./product_mark_sale").product_mark_sale,
    send_photo: require("./send_photo").send_photo,
    send_message: require("./send_message").send_message,
    send_mark_with_answer: require("./send_mark_with_answer").send_mark_with_answer,
    send_thanks: require("./send_thanks").send_thanks,
    
};